import 'package:flutter/material.dart';

import 'report_setting_switch.dart';

class ReportSettingsVisibilitySwitches extends StatelessWidget {
  const ReportSettingsVisibilitySwitches({
    super.key,
    required this.showCompanyLogo,
    required this.showCompanyDetails,
    required this.showDocumentControl,
    required this.showGeneratedBy,
    required this.onShowCompanyLogoChanged,
    required this.onShowCompanyDetailsChanged,
    required this.onShowDocumentControlChanged,
    required this.onShowGeneratedByChanged,
  });

  final bool showCompanyLogo;
  final bool showCompanyDetails;
  final bool showDocumentControl;
  final bool showGeneratedBy;
  final ValueChanged<bool> onShowCompanyLogoChanged;
  final ValueChanged<bool> onShowCompanyDetailsChanged;
  final ValueChanged<bool> onShowDocumentControlChanged;
  final ValueChanged<bool> onShowGeneratedByChanged;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        ReportSettingSwitch(
          title: 'Show Company Logo',
          value: showCompanyLogo,
          onChanged: onShowCompanyLogoChanged,
        ),
        ReportSettingSwitch(
          title: 'Show Company Details',
          value: showCompanyDetails,
          onChanged: onShowCompanyDetailsChanged,
        ),
        ReportSettingSwitch(
          title: 'Show Document Control',
          value: showDocumentControl,
          onChanged: onShowDocumentControlChanged,
        ),
        ReportSettingSwitch(
          title: 'Show Generated By',
          value: showGeneratedBy,
          onChanged: onShowGeneratedByChanged,
        ),
      ],
    );
  }
}
