import 'package:flutter/material.dart';
import 'package:gap/gap.dart';

import 'report_setting_switch.dart';
import 'package:mina_system/core/theme/app_icons.dart';

class ReportSettingsVisibilitySwitches extends StatelessWidget {
  const ReportSettingsVisibilitySwitches({
    super.key,
    required this.showCompanyLogo,
    required this.showCompanyDetails,
    required this.showDocumentControl,
    required this.showGeneratedBy,
    required this.onShowCompanyLogoChanged,
    required this.onShowCompanyDetailsChanged,
    required this.onShowDocumentControlChanged,
    required this.onShowGeneratedByChanged,
  });

  final bool showCompanyLogo;
  final bool showCompanyDetails;
  final bool showDocumentControl;
  final bool showGeneratedBy;
  final ValueChanged<bool> onShowCompanyLogoChanged;
  final ValueChanged<bool> onShowCompanyDetailsChanged;
  final ValueChanged<bool> onShowDocumentControlChanged;
  final ValueChanged<bool> onShowGeneratedByChanged;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final options = [
          _ReportVisibilityOption(
            title: 'Company Logo',
            description: 'Show the company logo in generated reports.',
            icon: AppIcons.image,
            value: showCompanyLogo,
            onChanged: onShowCompanyLogoChanged,
          ),
          _ReportVisibilityOption(
            title: 'Company Details',
            description: 'Include company identity and contact details.',
            icon: AppIcons.businessOutlined,
            value: showCompanyDetails,
            onChanged: onShowCompanyDetailsChanged,
          ),
          _ReportVisibilityOption(
            title: 'Document Control',
            description: 'Show document code, issue, and revision data.',
            icon: AppIcons.ruleFolderOutlined,
            value: showDocumentControl,
            onChanged: onShowDocumentControlChanged,
          ),
          _ReportVisibilityOption(
            title: 'Generated By',
            description: 'Display generated-by details on reports.',
            icon: AppIcons.personSearchOutlined,
            value: showGeneratedBy,
            onChanged: onShowGeneratedByChanged,
          ),
        ];

        if (constraints.maxWidth >= 1200) {
          return Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              for (var index = 0; index < options.length; index++) ...[
                Expanded(child: _buildSwitch(options[index])),
                if (index != options.length - 1) const Gap(12),
              ],
            ],
          );
        }

        if (constraints.maxWidth >= 720) {
          final itemWidth = (constraints.maxWidth - 12) / 2;

          return Wrap(
            spacing: 12,
            runSpacing: 12,
            children: options.map((option) {
              return SizedBox(width: itemWidth, child: _buildSwitch(option));
            }).toList(),
          );
        }

        return Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            for (var index = 0; index < options.length; index++) ...[
              _buildSwitch(options[index]),
              if (index != options.length - 1) const Gap(12),
            ],
          ],
        );
      },
    );
  }

  Widget _buildSwitch(_ReportVisibilityOption option) {
    return ReportSettingSwitch(
      title: option.title,
      description: option.description,
      icon: option.icon,
      value: option.value,
      onChanged: option.onChanged,
    );
  }
}

class _ReportVisibilityOption {
  const _ReportVisibilityOption({
    required this.title,
    required this.description,
    required this.icon,
    required this.value,
    required this.onChanged,
  });

  final String title;
  final String description;
  final IconData icon;
  final bool value;
  final ValueChanged<bool> onChanged;
}
